import { useState } from 'react';

import { Button, Card } from '../components/ui';
import { Brand } from '../components/icons';
import { useAuth } from '../lib/auth';

/**
 * Shown before anything else to an admin whose account was created during
 * estate onboarding.
 *
 * That password was generated by the platform owner, read off a screen and
 * passed on — by the time it is first used at least two people know it. This is
 * where it stops being the handover password and becomes theirs.
 *
 * It is a prompt rather than a wall: the person who could route around it is
 * the person the password was given to, and they already own the account. What
 * it prevents is the handover password quietly staying in place for a year.
 */
export function ChangePassword() {
  const { session, changePassword, signOut } = useAuth();
  const [next, setNext] = useState('');
  const [again, setAgain] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const submit = async () => {
    if (next.length < 8) {
      setError('Use at least 8 characters.');
      return;
    }
    if (next !== again) {
      setError('The two passwords do not match.');
      return;
    }
    setBusy(true);
    setError(null);
    const { error: err } = await changePassword(next);
    setBusy(false);
    if (err) setError(err);
  };

  return (
    <div className="flex min-h-screen items-center justify-center bg-ink p-6">
      <Card className="w-full max-w-[420px] p-8">
        <div className="flex items-center gap-2.5">
          <div className="flex h-[30px] w-[30px] items-center justify-center rounded-[10px] bg-lime">
            <Brand />
          </div>
          <div className="text-[15px] font-extrabold tracking-tight">Estate Access</div>
        </div>

        <h1 className="mt-7 text-[24px] font-extrabold tracking-tight">Choose your own password</h1>
        <p className="mt-2 text-[13px] leading-[19px] text-muted">
          Your account was opened with a password someone read out to you. Replace it before you
          start — anyone who saw it can currently sign in as you.
        </p>

        <div className="mt-6 space-y-3">
          <input
            type="password"
            autoFocus
            value={next}
            onChange={(e) => setNext(e.target.value)}
            placeholder="New password"
            autoComplete="new-password"
            className="h-11 w-full rounded-[14px] bg-field px-4 text-[13px] outline-none focus:ring-2 focus:ring-lime"
          />
          <input
            type="password"
            value={again}
            onChange={(e) => setAgain(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && void submit()}
            placeholder="Repeat it"
            autoComplete="new-password"
            className="h-11 w-full rounded-[14px] bg-field px-4 text-[13px] outline-none focus:ring-2 focus:ring-lime"
          />
        </div>

        {error ? (
          <div className="mt-3 rounded-[12px] bg-coral-soft px-3.5 py-2.5 text-[12.5px] font-semibold text-coral-ink">
            {error}
          </div>
        ) : null}

        <Button onClick={() => void submit()} disabled={busy} className="mt-5 h-11 w-full justify-center">
          {busy ? 'Saving…' : 'Save and continue'}
        </Button>

        <div className="mt-4 flex items-center justify-between text-[11.5px] text-muted">
          <span className="truncate">{session?.user.email}</span>
          <button type="button" onClick={() => void signOut()} className="font-bold hover:text-ink">
            Sign out
          </button>
        </div>
      </Card>
    </div>
  );
}
